begin;

-- Local pickup, part 1: the static safe-trade-station reference data, the two new listings
-- columns, and create_listing_with_details gaining pickup params. Pickup is an ADDITIONAL
-- checkout choice alongside shipping, not a replacement -- weight/dims stay required on every
-- listing exactly as before. See 202609300059/202609300060 for checkout and escrow-release.

create table public.pickup_stations(
  id uuid primary key default gen_random_uuid(),
  jurisdiction text not null,
  city text,
  state text,
  country text not null default 'USA',
  notes text,
  created_at timestamptz not null default now()
);
create index pickup_stations_country_state on public.pickup_stations(country, state);
alter table public.pickup_stations enable row level security;
revoke all on public.pickup_stations from public,anon,authenticated;
-- Static, non-sensitive reference data (public safe-exchange-zone addresses) -- readable by
-- anyone, writable by nobody from the client, same posture as listing_media's read policy but
-- with a `true` predicate since there's no per-row ownership to scope by.
create policy pickup_stations_public_read on public.pickup_stations for select to anon, authenticated using (true);
grant select on public.pickup_stations to anon, authenticated;

-- Seed data generated from a cleaned, deduplicated real-world dataset of "safe exchange zone"
-- locations (mostly US police stations, some Canada/Brazil) via a one-off script rather than
-- hand-typed -- see the migration's originating conversation for the cleanup performed
-- (duplicate rows dropped, two rows with a blank Country defaulted to USA, one row's Notes field
-- had unrelated chat text stripped out, a couple of run-together Jurisdiction/City pairs split).
insert into public.pickup_stations(jurisdiction,city,state,country,notes) values
('North Pole Police Department','North Pole','AK','USA','Lit parking lot 8 AM - 5 PM weekends. 10 AM - 5 PM weekdays. 24/7 video surveillance and designated parking spots.'),
('Alabaster Police Department','Alabaster','AL','USA','multiple surveillance cameras, which record 24 hours a day'),
('Madison Police Department','Madison','AL','USA','Lobby of the Madison PD on Hughes Road open 24 hours a day. Personnel monitor the windows during normal business hours. After hours, the lobby is under constant video surveillance. A phone in the lobby provides direct access to MPD dispatch in case of emergency.'),
('Montgomery Police Department','Montgomery','AL','USA',null),
('Batesville Police Department','Batesville','AR','USA','Parking spaces with video surveillance'),
('Camden Police Department','Camden','AR','USA',null),
('Clarksville Police Department','Clarksville','AR','USA','Designated parking spots'),
('Fort Smith Police Department','Fort Smith','AR','USA','Lobby during business hours, 8 a.m. to 7 p.m. M-Th, and 8 a.m. to 6 p.m. Fridays, plus designated parking spots'),
('Greenwood Police Department','Greenwood','AR','USA','Designated parking spots'),
('Jacksonville Police Department','Jacksonville','AR','USA',null),
('Jonesboro Police Department','Jonesboro','AR','USA','Designated parking spots'),
('Maumelle Police Department','Maumelle','AR','USA','Parking lot available for use.'),
('Springdale Police Department','Springdale','AR','USA','Parking spaces with 24 hour video surveillance'),
('Willcox Police Department','Willcox','AZ','USA',null),
('Williams Police Department','Williams','AZ','USA','A "Meetup Spot" in the front parking area outside the police station is well lit and there is continuous surveillance 24 hours a day. No appointments are necessary. Officers do not get involved with any transactions.'),
('Benicia Police Department','Benicia','CA','USA','Designated Exchange Zone in front of the Police Station under 24/7 surveillance.'),
('Buena Park Police Department','Buena Park','CA','USA',null),
('Calaveras County Sheriff''s Office','San Andreas','CA','USA','Well-lit, marked parking spaces on your right side before exiting the Sheriff''s Office parking lot. There are two parking spaces on each side of the light pole with a SafeTrade sign identifying the spaces. Monitored by surveillance cameras 24 hours a day.'),
('Chico Police Department','Chico','CA','USA',null),
('Clovis Police Department','Clovis','CA','USA','Parking lot in front of department under 24-hour video surveillance.'),
('Daly City Police Department','Daly City','CA','USA','Two parking spots under round-the-clock surveillance directly in front of Daly City''s police station.'),
('Danville Police Department','Danville','CA','USA','Parking spaces watched by a hidden camera outside police headquarters at 510 La Gonda Way.'),
('Escondido Police Department','Escondido','CA','USA','Designated, well lit meeting spot in the station parking lot under 24/7 surveillance'),
('Fremont Police Department','Fremont','CA','USA','2 marked spaces in the Police Dept. front lot under recorded video/audio surveillance 24/7'),
('Indio Police Department','Indio','CA','USA','Signed area of the PD parking lot reserved for exchanges'),
('Irvine Police Department','Irvine','CA','USA','Designated E- commerce spots under surveillance 24/7 outside the department at Civic Center Plaza'),
('Lake Elsinore','Riverside County','CA','USA','Designated spot outside the Sheriff''s station'),
('Los Angeles Police Department Southwest Area','Los Angeles','CA','USA','E-Commerce Exchange Zones available 24-7 within the police station lobby.'),
('Los Angeles Police Department Harbor Area','Los Angeles','CA','USA','E-Commerce Exchange Zones available 24-7 within the police station lobby.'),
('Los Angeles Police Department 77th Street Area','Los Angeles','CA','USA','E-Commerce Exchange Zones available 24-7 within the police station lobby.'),
('Los Angeles Police Department Southeast Area','Los Angeles','CA','USA','E-Commerce Exchange Zones available 24-7 within the police station lobby.'),
('Los Angeles Police Department Hollywood Area','Los Angeles','CA','USA','E-Commerce Exchange Zones available 24-7 within the police station lobby.'),
('Los Angeles Police Department Wilshire Area','Los Angeles','CA','USA','E-Commerce Exchange Zones available 24-7 within the police station lobby.'),
('Los Angeles Police Department West L.A. Area','Los Angeles','CA','USA','E-Commerce Exchange Zones available 24-7 within the police station lobby.'),
('Los Angeles Police Department Pacific Area','Los Angeles','CA','USA','E-Commerce Exchange Zones available 24-7 within the police station lobby.'),
('Los Angeles Police Department Olympic Area','Los Angeles','CA','USA','E-Commerce Exchange Zones available 24-7 within the police station lobby.'),
('Madeira Police Department','Fresno','CA','USA','Marked parking spaces monitored by surveillance cameras 24 hours a day'),
('Mammoth Lakes Police Department',null,'CA','USA','Lobby during business hours (M-Thurs 8-5).'),
('Fontana Police Department','Fontana','CA','USA','Parking lot located at 17005 Upland Ave. Officials prefer if residents complete the transactions during regular business hours'),
('Moreno Valley Police Department','Moreno Valley','CA','USA','Swap Zone is at 22850 Calle San Juan de Los Lagos and offers distinct signage and is monitored by a Citywide Camera to record transactions.'),
('Pittsburg Police Department','Pittsburg','CA','USA','An "exchange zone" in front of the City Hall and police station offers two specially-marked parking spaces, each with an "exchange zone" sign saying the area "has been designated for conducting private property transactions." The zone is well-lighted and monitored around the clock by surveillance cameras.'),
('Rancho Peñasquitos Police Department','San Diego','CA','USA','Well-lit, marked parking spaces are monitored by surveillance cameras 24 hours a day, and are in clear view of the front doors of the Northeastern Division station.'),
('San Diego Police Department','San Diego','CA','USA','8 Divisions have well-lit designated areas in front of the police departments front doors.'),
('San Mateo County Sheriff''s Office','San Mateo','CA','USA','The exchange zone is at the Maple Street Correctional Center in Redwood City. The new jail has 24-hour video surveillance, has a heavy law enforcement presence and is across the street from the Redwood City Police Department.'),
('San Mateo Police Department','San Mateo','CA','USA','Designated area in the main lobby entrance of the Franklin Parkway station- under 24 hr. surveillance.'),
('Signal Hill Police Department','Signal Hill','CA','USA','2745 Walnut Ave, Signal Hill, CA 90755. Trades can be made in the public parking lot in front of the station.'),
('Santa Ana Police Department','Santa Ana','CA','USA','The Santa Ana Police Department is now open as an E-Commerce Exchange Zone on our front steps. Park in front of the police station and complete your transaction in our well-lit, camera-monitored area. You''re also welcome to use our lobby as an exchange location during business hours.'),
('Colorado Springs Police Department','Colorado Springs','CO','USA','Trade zone in police station and parking lot under video surveillanve'),
('Denver Police Department','Denver','CO','USA','Districts 1-6 will have painted parking spaces under 24/7 surveillance and a sign posted on the stations'' doors. Parking spaces are currently identified iwith temporary signs in Spanish and English.'),
('Douglas County Justice Center','Denver','CO','USA','Parking spaces at the Douglas County Justice Center and at Highlands Ranch Substation'),
('Estes Park Poice Department','Estes Park','CO','USA','Two parking spots directly in front of the Police Department. 24 hour video surveillance. PD lobby available 24/7 with video surveillance.'),
('Fort Collins Police Service','Fort Collins','CO','USA','Lobby 8 a.m. to 8 p.m. M-F or 8 a.m. to 6 p.m. Sat. and Sun. The north public parking lot of the police station can be used 24/7. Both areas are well-lit with video surveillance.'),
('Greenwood Village Police Department','Greenwood Village','CO','USA','City Hall parking lots are under surveillance 24/7'),
('Connecticut State Police Barracks','Statewide','CT','USA','Parking spaces'),
('Cromwell Police Department','Cromwell','CT','USA','Parking spaces'),
('Darien Police Department','Darien','CT','USA','Parking lot on the south side of the building, marked with sign. This area is monitored 24 hours a day by video surveillance and is recorded.'),
('Easton Police Department','Easton','CT','USA','Parking lot across from police station. Sign and cameras'),
('Glastonbury Police Department','Glastonbury','CT','USA','2 Designated parking spots in the police lot under surveillance.'),
('Guilford Police Department','Guilford','CT','USA','Two parking spaces prominently placed in front of cameras'),
('Hartford Police Department','Hartford','CT','USA',null),
('Monroe Police Department','Monroe','CT','USA','Marked Safe exchange Zone outside the department''s front entrance under video surveillance 24/7.'),
('Montville Police Department','Montville','CT','USA','parking lot and lobby at the public safety building. 24 hour surveillance'),
('New London Police Department','New London','CT','USA','lobby and parking lot are under 24-hour video surveillance'),
('Newington Police Department','Newington','CT','USA','Parking space'),
('Waterford Police Department','Waterford','CT','USA','lobby or the front parking lot of the police department'),
('West Hartford Police Department','West Hartford','CT','USA',null),
('Wilton Police Department','Wilton','CT','USA','Parking lot in front of headquarters at 240 Danbury Road. Are designated by sign that indicates 24-hour surveillance.'),
('Metropolitan Police Department','Washington','DC','USA','Special Operations Division''s Harbor Patrol; Third and Sixth District stations'),
('Greenwood Police Department','Greenwood','DE','USA','Lobby M-F 8am-5pm or in our parking lot.'),
('Alachua County Sheriff''s Office',null,'FL','USA','24-hour use of parking lot.'),
('Boca Raton Police Department','Boca Raton','FL','USA','Signs posted outside designating areas that are under constant video surveillance'),
('Boynton Beach Police Department','Boynton Beach','FL','USA','Signs posted outside designating areas that are under constant video surveillance'),
('Brevard County Sheriff''s Office',null,'FL','USA','The Sheriff''s Office established internet safe zones for its precincts in Melbourne, Titusville, Merritt Island and Viera. Each location has survelliance cameras.'),
('Bradford County Sheriff''s Office',null,'FL','USA',null),
('Broward Sheriff''s Office Tamarac District',null,'FL','USA','Signs posted outside designating areas that are under constant video surveillance'),
('Washington County Sheriff''s Office','Chipley','FL','USA','"Safe Exchange Zones," designated parking spaces located just off the sheriff''s office Third Street entrance. The parking spaces are under 24-hour video surveillance.'),
('Cocoa Police Department','Cocoa','FL','USA','Internet Purchase Exchange Zone at police headquarters, 1226 W. King St. The east parking lot of the building is a well-lighted area that is under 24-hour video surveillance.'),
('Coral Springs Police Department','Coral Springs','FL','USA','Signs posted outside designating areas that are under constant video surveillance'),
('Crestview Police Department','Crestview','FL','USA','Under 24-hour daily video surveillance, the CPD "safe swap zone" is in a well-lit west section of the parking lot right in front of the Whitehurst Municipal Building, 201 Stillwell Blvd.'),
('Dade City','Dade City','FL','USA',null),
('FIU Police Department','Miami','FL','USA',null),
('Delray Beach Police Department','Delray Beach','FL','USA','Signs posted outside designating areas that are under constant video surveillance'),
('Flagler Beach Police Department','Flagler Beach','FL','USA',null),
('Gainesville Police Department','Gainesville','FL','USA',null),
('Gilchrist County Sheriff''s Office',null,'FL','USA','24-hour use of parking lot.'),
('Hall County Sheriff''s Office',null,'FL','USA','Lobby available any time during business hours.'),
('Hillsborough County Sheriff''s Office',null,'FL','USA',null),
('Jacksonville Sheriff''s Office','Jacksonville','FL','USA',null),
('Lady Lake Police Department','Lady Lake','FL','USA','Lobby M-Th, 7 a.m. to 6 p.m. Parking lot 24/7. No appointment is necessary.'),
('Lakeland Police Department','Lakeland','FL','USA',null),
('Melbourne Police Department','Melbourne','FL','USA','Police department lobby at 650 N. Apollo Boulevard available as a rendezvous point.'),
('Miami-Dade Police Department',null,'FL','USA',null),
('Miami Beach Police Department','Miami Beach','FL','USA',null),
('Manatee County Sheriff''s Office',null,'FL','USA','Facility open 24/7, 365'),
('North Miami Police Department','Miami','FL','USA','2 parking spots'),
('Ocala Police Department','Ocala','FL','USA','E-Commerce Exchange Zone in the parking lot at Police Department headquarters under surveillance 24/7'),
('Orange park Police Department','Orange Park','FL','USA','Exchanges can take place in the lobby or parking lot of the Police Department 8am to 9pm daily.'),
('Pinellas County Sheriff''s Dept.','Oldsmar','FL','USA','Oldsmar City Hall. Hours would be 8am-5pm ET Monday-Friday (except holidays)'),
('Palm Beach Sheriff''s Office','Palm Beach','FL','USA','Signs posted outside designating areas that are under constant video surveillance'),
('Pembroke Pines','Broward','FL','USA','Designated spots outside, with signs and 24 hour video surveillance at police headquarters and the West Side substation.'),
('Pensacola Police Dept.','Pensacola','FL','USA','There is a place in the lobby with sworn officer present 24/7.'),
('Pinecrest Police Department','Pinecrest','FL','USA','Parking lot and lobby 24/7'),
('Sarasota Police Department','Sarasota','FL','USA','Transactions can be completed in the police department lobby.'),
('St. Augustine Police Department','St Augustine','FL','USA',null),
('Sunrise Police Department','Sunrise','FL','USA','Signs posted outside designating areas that are under constant video surveillance.'),
('Hillsborough County Sheriff''s Office District 1','Tampa','FL','USA','14102 N. 20th Street, Tampa, FL 33613. Area is equipped with signage and video cameras.'),
('Hillsborough County Sheriff''s Office District 2','Tampa','FL','USA','2310 N. Falkenburg Road, Tampa, FL 33619. Area is equipped with signage and video cameras.'),
('Hillsborough County Sheriff''s Office District 3','Tampa','FL','USA','7202 Gunn Highway, Tampa, FL 33625. Area is equipped with signage and video cameras.'),
('Hillsborough County Sheriff''s Office District 4','Tampa','FL','USA','508 33rd Street SE, Ruskin, FL 33570. Area is equipped with signage and video cameras.'),
('Hillsborough County Sheriff''s Office District 5','Tampa','FL','USA','10128 Windhorst Road, Tampa, FL 33619. Area is equipped with signage and video cameras.'),
('Albany Police Department','Albany','GA','USA','Exchange zones in the West Oglethorpe PD parking lot and behind the Law Enforcement Center.'),
('Augusta (Richmond County)','Augusta','GA','USA','Two spaces outlines in yellow, with camera surveillance 24/7. One space outside the detention center, the other outside the Sheriff''s office. Signs identify spaces for Internet purchases.'),
('Chamblee Police Department','Chamblee','GA','USA',null),
('Cobb County Police Department','Atlanta','GA','USA','Well lit zones, designated with blue signs, under video surveillance'),
('Cobb County Police Department','Austell','GA','USA','Well lit zones, designated with blue signs, under video surveillance'),
('Cobb County Police Department','Kenesaw','GA','USA','Well lit zones, designated with blue signs, under video surveillance'),
('Cobb County Police Department','Marietta','GA','USA','Well lit zones, designated with blue signs, under video surveillance at Police Headquarters and Precinct 4'),
('Cobb County Police Department','Powder Springs','GA','USA','Well lit zones, designated with blue signs, under video surveillance'),
('Douglasville Police Department',null,'GA','USA','Designated parking area, well lit, under video surveillance. Main lobby area, under video surveillance also available for trades.'),
('Effingham Sheriff''s Office','Springfield','GA','USA','Designated area of their lot under video surveillance'),
('Floyd County Sheriff''s Office','Rome','GA','USA',null),
('Gainesville Police Department','Gainesville','GA','USA','Area of the parking lot under video surveillance and lobby during normal operating hours, Monday-Friday, 8am to 5pm'),
('Grovetown Department of Public Safety','Grovetown','GA','USA',null),
('LaGrange Police Department','LaGrange','GA','USA','Parking lot is under video surveillance'),
('LaFayette Police Department','LaFayette','GA','USA',null),
('Liberty County Sheriff''s Department','Hinesville','GA','USA','Designated parking area marked with red paint and a sign'),
('Troup County Sheriff''s Office',null,'GA','USA',null),
('Savannah Metro Crime Prevention','Savannah','GA','USA',null),
('Marietta police department','Marietta','GA','USA',null),
('Newnan Public Safety Center','Newnan','GA','USA',null),
('Kennesaw police','Kennesaw','GA','USA','Call in advance.'),
('Smyrna Police Department','Smyrna','GA','USA','Police officer present or in the well-lit parking lot'),
('Woodstock Police Department','Woodstock','GA','USA',null),
('Atlanta Police Department','Atlanta','GA','USA','All Atlanta Police Departments have Safe Exchange Zones that are well lit and monitored 24/7.'),
('Algona Police Department','Algona','IA','USA',null),
('Dubuque Law Enforcement Center','Dubuque','IA','USA',null),
('Marshalltown Police Department','Marshalltown','IA','USA','Trades can take place in the station lobby- under 24/7 video surveillance'),
('Osceola County Sheriff''s Department',null,'IA','USA',null),
('West Burlington Police Department','West Burlington','IA','USA','Lobby and four parking spaces available north of the front door to City Hall as well as the back parking lot of City Hall. Lobby open 7 a.m. to 5 p.m. Monday to Friday, except for holidays.'),
('Meridian Police Department','Meridian','ID','USA','Front parking lot, 24 hour surveillance'),
('Nampa Police Department','Nampa','ID','USA','Two parking spaces in the front parking lot'),
('Alton Police Department','Alton','IL','USA',null),
('Arlington Heights Police Department','Arlington Heights','IL','USA','Front desk manned 24/7 with designated front desk personnel. Lobby open and under 24/7 video surveillance.'),
('Bensenville Police Department','Bensenville','IL','USA','Station located in the lobby of the police department-lighted and video recorded.'),
('Bloomington Police Department','Bloominton','IL','USA','Monday through Friday, 7am to 11pm. No vehicles with trailers or vehicles over 8 feet 6 inches tall.'),
('Carbondale Police Department','Carbondale','IL','USA',null),
('Champaign Police Department','Champaign','IL','USA','Lobby available 24 hours a day.'),
('Clarendon Hills Police Department','Clarendon Hills','IL','USA',null),
('Decatur Police Department','Decatur','IL','USA','Lobby available 24 hours a day, but police recommend doing transactions between business hours of 8 a.m. to 5 p.m.'),
('DeKalb Police Department','DeKalb','IL','USA','Trades should be made in the front parking lot of the police department, on the east side. The area is under surveillance 24/7.'),
('Edwardsvile Police department','Edwardsville','IL','USA','Trades can be made in the lobby or parking lot. Lot has video surveillance and good lighting.'),
('Fairview Heights Police Department','Fairview Heights','IL','USA',null),
('Freeport Police Department','Freeport','IL','USA','Trades can be made in the front lobby of the Police Headquarters building. The area is under video surveillance 24/7/365 and is within view of our 9-1-1 center that is always staffed.'),
('Gurnee Police Department','Gurnee','IL','USA',null),
('Maryville Police Department','Marville','IL','USA','Lobby and parking lot available 24 hours a day. All sales are civil matters.'),
('Madison County Sheriff''s Office',null,'IL','USA',null),
('Glen Carbon Police Department','Glen Carbon','IL','USA',null),
('Naperville Police Department','Naperville','IL','USA',null),
('Oak Forest Police Department','Chicago','IL','USA','Lobby and parking lot'),
('O''Fallon Police Department','O''Fallon','IL','USA',null),
('St. Louis County Police Department',null,'IL','USA',null),
('Peoria Police Department','Peoria','IL','USA','All sales are civil matters. Officers should not be called on to intervene.'),
('Peoria County Sheriff''s Office',null,'IL','USA',null),
('Jackson Police Department','Jackson','IL','USA','Inform staff members of the planned transaction.'),
('East Chicago Police Department','East Chicago','IL','USA','Monday through Friday, 9am to 7pm. Saturday 11am to 3pm.'),
('Lake in the Hills Police Department','Lake in the Hills','IL','USA',null),
('Oak Park Police Station','Oak Park','IL','USA','Lobby is well-lit and staffed 24-hours a day'),
('Palatine Police Department','Chicago','IL','USA','A large sign designates a well-lit "Internet Purchase Exchange Zone" on the west side of the main police station parking lot, under 24-hour video surveillance.'),
('Randolph County Sheriff''s Office','Chester','IL','USA','Sheriff''s Office front lobby available 24 hours a day for internet purchases. No firearms sales in lobby. Parking area under surveillance for sales of larger items.'),
('Springfield Police Department','Springfield','IL','USA','Lobby available 24 hours a day.'),
('Town Hall District Police Station','Chicago','IL','USA','The police station lobby is available for exchanges daily between 9 a.m. and 7 p.m., and participants should let the desk person on duty know.'),
('Villa Park Police Department','Villa Park','IL','USA',null),
('Waukegan Police Department','Waukegan','IL','USA',null),
('Winthrop Harbor Police Department','Winthrop','IL','USA',null),
('Woodstock Police Department','Woodstock','IL','USA',null),
('Stephenson County Sherriff''s Office','Freeport','IL','USA','Trades can be made in the front lobby of the Stephenson County Sheriff''s Office Public Safety Building located at 204 W. Exchange St. in Freeport Illinois. The area is under video surveillance 24/7/365.'),
('Hamilton County Sheriff''s Department','Noblesville','IN','USA','2 reserved spots near the entrance of the Sheriff''s offices under 24 hour surveillance'),
('Hammond Police Department','Hammond','IN','USA','A "safe-exchange space" established at the department, 509 Douglas St., is marked with a green sign in the department''s east parking lot.'),
('Indianopolis Police Department','Indianapolis','IN','USA','e-commerce zones under 24 hour surveillance. Some stations have zones in the lobby during business hours, others reserved parking spaces.'),
('Jackson County Jail','Brownstown','IN','USA','Two reserved parking spots located under 24hour video surveillance'),
('LaPorte County Sheriff''s Office','LaPorte','IN','USA','24-hour lobby.'),
('Portage Police Department','Portage','IN','USA','Central Avenue station has stickers on the front and rear doors designating it as a SafeTrade area.'),
('St John Police Department','St John','IN','USA','Lobby 9am-6pm M-F; Sat 9am-1pm. Five spaces in lot marked with signage and covered by hi def cameras.'),
('Valparaiso Police Department','Valparaiso','IN','USA','Two dedicated parking spaces clearly marked by painted pavement and signs. Spaces are under 24/7 video surveillance.'),
('Whitestown police department','Whitestown','IN','USA','Monday through Friday, 9am to 5pm, Town hall lobby. Parking lot 24 / 7.'),
('South Bend Police Department','South Bend','IN','USA','There is a camera monitored exchange site in front of the South Bend Police Dept. 701 W Sample St, South Bend, IN 46601'),
('Andover Police Department','Andover','KS','USA','Two parking spaces outside the building'),
('Lyon''s County Sheriff''s Department','Emporia','KS','USA','Designated parking areas'),
('Overland Park Police Department','Overland Park','KS','USA','Lobby and lot, 24/7'),
('Wichita Police','Wichita','KS','USA','Monday through Friday, 8am to 5pm.'),
('Glasgow Police Department','Glasgow','KY','USA','2 Designated parking spots in a lighted area, in the Police Station parking lot, under video surveillance.'),
('Owensboro Police Department','Owensboro','KY','USA','Lobby and lot, 24/7; no trailers and large loads in lot'),
('Caddo Parish Sheriff''s Office',null,'LA','USA',null),
('Sheriff''s Training Academy','Luling','LA','USA','Parking lot entrance, 24/7 video surveillance'),
('Baton Rouge Police Department','Baton Rouge','LA','USA','Zone is setup in the northeast parking lot of police headquarters on Airline Highway. It''s monitored by surveillance cameras at all times. Police officers prefer people to finalize their transactions during daylight hours.'),
('St. Gabriel Police Department','St. Gabriel','LA','USA','Facility has 24 hour-surveillance for buyers and sellers to meet.'),
('Bedford Police Department','Bedford','MA','USA','Marked area in the Police station lobby with 24 hour surveillance.'),
('Bellingham Police Department','Bellingham','MA','USA','Spot is just outside the department where video cameras are monitoring the area 24/7.'),
('Boston Police Department','Boston','MA','USA','Designated Safe Exchange Zones with 24 hr surveillance at all district stations and Police headquarters'),
('Chelmsford Police Department','Chelmsford','MA','USA',null),
('Chicopee Police Department','Chicopee','MA','USA',null),
('Fitchburg Police Department','Fitchburg','MA','USA','2 designated parking spaces outside the police station with 24/7 monitoring.'),
('Georgetown Police Department','Georgetown','MA','USA',null),
('Groveland Police Department','Groveland','MA','USA','Meet Up Spot behind the police station with a surveillance camera'),
('Hopedale Police Department','Hopedale','MA','USA','Parking space available in front of station.'),
('Hopkington Police Department','Hopkington','MA','USA',null),
('Hudson Police Depatment','Hudson','MA','USA',null),
('Medfield Public Safety Building','Medfield','MA','USA',null),
('New Bedford Police Department','New Bedford','MA','USA','Parking lot of headquarters-871 Rockdale Ave'),
('Southborough Police Department','Southborough','MA','USA','Internet Exchange sign marks a lighted space, under 24/7 video surveillance, in the Public Safety Building parking lot.'),
('Swansea Police Department','Swansea','MA','USA','Front parking lot and inside the station under 24/7 surveillance.'),
('Yarmouth Police Department','Yarmouth','MA','USA','Parking spaces available in front of station.'),
('Upton Police Department','Upton','MA','USA','Parking space available in front of station.'),
('Winchendon Police Department','Winchendon','MA','USA',null),
('Annapolis Police Department','Annapolis','MD','USA','Lobby at 199 Taylor Ave. Conduct transaction in parking lot or lobby.'),
('Chestertown Police Department','Chestertown','MD','USA','Well lit parking lot with video surveillance 24/7. Transactions should be made in the parking lot area closest to the front doors and College Ave.'),
('Rockville Police Department','Rockville','MD','USA','Transactions may take place in the police station (staffed 24/7) or outside in the parking lot under video surveillance.'),
('University of MD Baltimore County Police','Baltimore Co.','MD','USA','Conduct transactions safely at the UMBC Police Station open 24/7.'),
('Auburn Police Department','Auburn','ME','USA',null),
('Augusta Police Department','Augusta','ME','USA','Lobby is open to the public 24 hours a day, seven days a week'),
('Paris Police Department','Paris','ME','USA','Lobby and parking lot M-F 8 am to 4 pm'),
('Rockland Police Department','Rockland','ME','USA','One in parking lot at 1 Police Plaza and the other is in J.C. Penney''s parking lot in the Rockland Plaza'),
('Scarborough Police Department','Scarborough','ME','USA','Visitor parking, monitored via a building-mounted camera by dispatchers in the Scarborough Public Safety Building, staffed 24-seven'),
('South Portland Police Department','South Portland','ME','USA','Lobby and parking lot'),
('Beverly Hills Police Department','Beverly Hills','MI','USA','East Parking Lot is open to the general public- under 24 hr surveillance. For small items- access to lobby is available by request. Lobby is under 24/7 surveillance.'),
('Argentine Township Police Department','Argentine Township','MI','USA','A sign in the parking lot notes it is a safe place under video surveillance.'),
('Delta Township Sheriff''s Office','Delta Township','MI','USA','Signs in parking lot'),
('Escanaba Department of Public Safety','Escanaba','MI','USA','East/Public parking lot 24 hours, 7 days a week for exchanges. All exchanges shall be conducted in the parking lot and not within the police department.'),
('Fenton Police Department','Fenton','MI','USA',null),
('Kent County Police Department',null,'MI','USA','Monday through Friday, 8am to 5pm.'),
('Livonia Police Department','Livonia','MI','USA','Will perform a serial or identification number check to see if the item is registered as stolen.'),
('Lowell Police Department','Lowell','MI','USA','Monday through Friday, 8am to 5pm.'),
('Ferndale Police Department','Ferndale','MI','USA',null),
('Grosse Pointe Woods Public Safety Department','Grosse Pointe Woods','MI','USA',null),
('Lake Odessa Police Department','Lake Odessa','MI','USA','Exchanges can be done in the Police Dept. lobby during regular business hours or in the parking lot anytime. Signed space at Lake Odessa Park under 24/7 video surveillance.'),
('Lansing Police Department Operations Center','Lansing','MI','USA',null),
('Menominee Police Department','Menominee','MI','USA','Lobby 8:30 a.m.to 5 p.m. Monday through Friday. Also parking area located directly in front of the Police and Fire Department.'),
('Norton Shores Police Department','Muskegon County','MI','USA','2 well lit spaces in the PD parking lot under video surveillance'),
('Novi Police Department','Novi','MI','USA',null),
('Oakland County Sheriff''s Office','Rochester Hills','MI','USA','Substation provides an e-commerce safety zone with 24-hour video surveillance. Two well-lighted, green-striped parking spots are located near the front door of the substation, next to the handicapped spots.'),
('Redford Police Department','Redford','MI','USA',null),
('Shelby Township Police Department','Shelby Township','MI','USA',null),
('Southfield Police Department','Southfield','MI','USA',null),
('Sterling Heights Police Department','Sterling Heights','MI','USA',null),
('Troy Police Department','Troy','MI','USA',null),
('Utica police department','Utica','MI','USA',null),
('West Bloomfield Police Department','West Bloomfield','MI','USA',null),
('Prior Lake Police Department','Prior Lake','MN','USA','Yellow signs identify a section of the parking lot under video surveillance 24/7 at the Dakota St. station.'),
('Big Lake Police Department','Big Lake','MN','USA','Two dedicated parking spaces highlighted with green striping and signs identifying them as a Meet-Up Spot. The spaces are covered by 24/7 video surveillance.'),
('Wilkin County Sheriff''s Office','Breckenridge','MN','USA','Safe Trade Zone sign posted at parking lot'),
('Ballwin Police Department','Ballwin','MO','USA','Lobby has camera and dispatch 24/7, and is manned from 8am to 5pm. There are 2 parking lots with videos.'),
('Columbia Police Department','Columbia','MO','USA','Lobby is open 24 / 7. No exchanging weapons.'),
('Chesterfield Police Department','Chesterfield','MO','USA',null),
('Clay County Sheriff''s Office',null,'MO','USA',null),
('Jefferson County Sheriff''s Office',null,'MO','USA','Inform staff members of the planned transaction.'),
('Lee''s Summit Police Department','Lee''s Summit','MO','USA','North side of front parking lot'),
('Moberly Police Department','Moberly','MO','USA',null),
('Nixa Police Department','Nixa','MO','USA','Parking space in front of station is well-lit and under 24-7 video surveillance.'),
('North Kansas City Police Department','North Kansas City','MO','USA','The police lobby is available 24 hours a day, 7 days a week.'),
('O''Fallon Police Department','O''Fallon','MO','USA',null),
('Ozark Police Department','Ozark','MO','USA','Two spaces outside police station with signs and constant surveillance. Site has 24 hour monitoring.'),
('Peculiar Police Department','Peculiar','MO','USA','Front parking lot'),
('Fairview Heights Police Department','Fairview Heights','MO','USA',null),
('Springfield Police Department','Springfield','MO','USA','The parking lot may be used by citizens at any time, and the building''s lobby is open from 7 a.m.-11 p.m.'),
('Wentzville Police Department','Wentzville','MO','USA','Inform staff members of the planned transaction.'),
('Willard Police Department','Willard','MO','USA',null),
('Excelsior Springs Police Department','Excelsior Springs','MO','USA','301 S Main St, Excelsior Springs, MO 64024. Transactions can be made in the lobby or parking lot of the police department. Both under 24/7 surveillance.'),
('Ashland MO Police Department','Ashland','MO','USA','We have a lighted area under video surveillance in our parking lot at 101 W. Broadway Ashland, MO 65010.'),
('Tupelo Police Department','Tupelo','MS','USA',null),
('Black Mountain Police Department','Black Mountain','NC','USA','A designated area in the parking lot of the Public Safety Bldg open 24/7, w/o surveillance. An additional lot adjacent to the public safety bldg. lot accommodates large vehicles.'),
('Burlington Police Department','Burlington','NC','USA','Designated parking spots'),
('Charlotte-Mecklenburg Police Departments','Charlotte','NC','USA',null),
('Carolina Beach Police Department','Carolina Beach','NC','USA','Designated parking with Safe Trade Logo signage in front of Police Dept. main entrance. High visibility, lit area with public view from street and video surveillance.'),
('Chapel Hill','Chapel Hill','NC','USA',null),
('Durham','Durham','NC','USA','Safe Haven for Sales- Make an appointment with the Sheriff''s dept., and an officer will be present at your sale in the County courthouse parking lot.'),
('Durham County Justice Center','Durham','NC','USA','Parking lot under the watchful eye of Deputy by appointment only. Weekdays 6pm to 9pm and weekend 9am to 9pm.'),
('Goodlettsville Police department','Goodlettsville','NC','USA','Parking Lot'),
('Greenville County Sheriff''s Office',null,'NC','USA',null),
('Greensboro Police Department','Greensboro','NC','USA',null),
('Hendersonville Police Department','Hendersonville','NC','USA','parking lot'),
('Jacksonville Police Department','Jacksonville','NC','USA','Exchange Site in the parking lot of the Public Safety Department building-monitored 24/7.'),
('La Vergne Police Department','La Vergne','NC','USA','parking lot'),
('Lee County Sherrif''s Office',null,'NC','USA','Monday through Friday 8am - 4pm by appointment only'),
('Spring Hill Police Department','Spring Hill','NC','USA','parking lot'),
('Wake Forest Police Department','Wake Forest','NC','USA',null),
('Fargo Police Department','Fargo','ND','USA','Meet at the Fargo police station on 25th and 13th. There is an internet purchase exchange location where there are cameras watching.'),
('Douglas County Sheriff''s Department',null,'NE','USA','Monday through Friday, 8am to 4pm.'),
('Lincoln Police Department','Lincoln','NE','USA','Two well lit, surveillance monitored parking spots outside the Center Street substation. Transactions can be made in the station during business hours.'),
('Hampton Police Department','Hampton','NH','USA','Safe space in parking lot in front of the police station at 100 Brown Ave.'),
('Hillsborough Police Department','Hillsborough','NH','USA','Visitor lot monitored by security cameras and is well lit. Transactions involving firearms or illegal items are not allowed.'),
('Manchester Police Department','Manchester','NH','USA','24 hour surveillance in the police department parking lot.'),
('Portsmouth Police Department','Portsmouth','NH','USA',null),
('Rindge Police Department','Rindge','NH','USA','2 designated Safe Exchange spaces in the station parking lot with 24/7 video surveillance.'),
('Seabrook Police Department','Seabrook','NH','USA','"Meetup Spot" sign in the parking lot.'),
('Allendale Police Department','Allendale','NJ','USA','Front lobby and in parking lot, indicated by sign, well-lit and monitored by video.'),
('Beachwood Police Department','Beachwood','NJ','USA','Designated parking spot under video surveillance 24/7. Lobby of Police Station is open for trades M-F 8am-4 pm.'),
('Bloomingdale Police Department','Bloomingdale','NJ','USA','In the rear of the Borough Hall parking lot near the police station. Area is well-lit and monitored by video.'),
('Bordentown Township Police Department','Bordentown','NJ','USA','Lobby, 24 hours a day'),
('Brick Police Department','Brick','NJ','USA','Signed space behind the town hall - monitored by cameras 24/7.'),
('Bridgeton Police Department','Bridgeton','NJ','USA','Parking spaces with video surveillance'),
('Butler Police Department','Butler','NJ','USA',null),
('Cherry Hill Police Department','Cherry Hill','NJ','USA','One safe zone is in the police headquarters lobby, accessible 24 hours a day. The second safe zone is located in the back lot at town hall. Both continuously monitored by surveillance cameras.'),
('Chester Borough Police Department','Chester','NJ','USA','A spot outside of the Chester Borough Police Department'),
('Closter Police Department','Closter','NJ','USA',null),
('Cumberland County Sheriff''s Department','Bridgeton','NJ','USA','Parking spaces with video surveillance'),
('Denville Police Department','Denville','NJ','USA',null),
('East Brunswick Police Department','East Brunswick','NJ','USA','2 marked spaces in the parking lot of the Municipal Court next to Police Headquarters 8:30 a.m. to 11 p.m., 7 days a week. Police lobby available during non-court hours by appointment.'),
('Elizabeth Police Department','Elizabeth','NJ','USA','Dedicated Safe Exchange Zone outside the police station under 24/7 surveillance.'),
('Evesham Township Police Department','Evesham','NJ','USA',null),
('Fanwood Police Department','Fanwood','NJ','USA','Transactions area is located to the left of the front door of police headquarters. Area is monitored by a 24-hour surveillance camera.'),
('Glen Rock Police Department','Glen Rock','NJ','USA','Designated offerup MeetUp spot outside the Borough Hall'),
('Hackensack Police Department','Hackensack','NJ','USA','2 designated parking spaces in the station parking lot, under 24 hr. surveillance'),
('Hillsdale Police Department','Hillsdale','NJ','USA','Lobby and rear parking lot'),
('Livingston Police Department','Livingston','NJ','USA',null),
('Lyndhurst Police Department','Lyndhurst','NJ','USA','Two well-lit designated parking spots behind Police Headquarters monitored with video surveillance. Residents can use the police department lobby as well to make the exchange.'),
('Millville Police Department','Millville','NJ','USA','Parking spaces with video surveillance'),
('Paulsboro Police Department','Paulsboro','NJ','USA','Lobby of police headquarters'),
('Robbinsville Police Department','Robbinsville','NJ','USA','Parking lot, 24-hour surveillance'),
('Vineland Police Department','Vineland','NJ','USA','Parking spaces with video surveillance'),
('South Brunswick Police Department','South Brunswick','NJ','USA','Two spots in parking lot. 15 minute limit.'),
('Washington Township Police Department','Long Valley','NJ','USA','Two designated, signed, monitored parking spaces in front of headquarters. Lobby open during daylight hours, visitors must be buzzed in at night.'),
('West Orange Police Department','West Orange','NJ','USA','Lobby of headquarters and substations from 8:30 a.m. to 4:30 p.m., Monday through Friday, and parking lots'),
('Woodland Park Police Department','Woodland Park','NJ','USA','Parking lot and vestibule of the police department building'),
('Mantua Township Police Department','Mantua','NJ','USA','405 Main Street, Mantua, NJ 08051. Our spots are specifically lit, recorded, and marked out as safe transaction spots.'),
('Farmington Police Department','Farmington','NM','USA','Designated parking spaces in front of station at 800 Municipal Drive. 24 hour surveillance.'),
('Los Lunas Police Department','Los Lunas','NM','USA',null),
('Nevada','Statewide','NV','USA','By September 2017, all counties will be required to have SafeTrade zones.'),
('North Las Vegas Police Area Command Sites','Las Vegas Valley','NV','USA','Northwest Area Command parking lot: 3755 W. Washburn Rd. South Area Command Parking lot: 2322 N. Las Vegas Blvd.'),
('Batavia Police Department','Batavia','NY','USA','Space at rear vestibule, at the north side of the police department under video surveillance with a direct-connect phone dispatch. Station open M-F, 8:30am to 4:30pm.'),
('Cheektowaga Police Department','Cheektowaga','NY','USA','The Police station is a designated Safe Trade Station. Parking lot and lobby available for trades and under 24/7 video surveillance.'),
('Coxsackie Police Dept.','Coxsackie','NY','USA','Labelled spots at the Village Hall "20 steps" from the Police Station. Site to have 24/7 camera surveillance.'),
('Depew Police Department','Depew','NY','USA','Marked area in the Police Station lobby during regular hours. After hours, 2 designated spots outside the Depew municipal building.'),
('Great Barrington Police Department','Great Barrington','NY','USA','Front lobby and parking lot are under 24/7 video surveillance'),
('Irondequoit Police Department','Irondequoit','NY','USA','2 monitored parking spots in front of the Police Station.'),
('LeRoy Police Department','LeRoy','NY','USA','Signed spaces in parking lot under 24/7 CCTV recording.'),
('Livingston County Sheriff''s Office',null,'NY','USA',null),
('Lyons Police Department','Wayne County','NY','USA','2 monitored parking spots, with signs, outside the Wayne County Jail'),
('Mahopac Police Department','Carmel and Mahopac','NY','USA','2 signs designating a monitored exchange area in the Town Hall/Police Quarter''s parking lot.'),
('Suffolk County Sheriff''s Office','Riverhead/Yaphank','NY','USA','Designated parking spaces'),
('City of Tonawanda','Tonawanda','NY','USA','2 parking spots labeled as Exchange Zones. Lighted and under video surveillance 24/7.'),
('Wayne County','Wayne County','NY','USA','2 identified parking spots in front of the Wayne County Sheriff''s Office Jail Facility under 24/7 video surveillance'),
('Elmira Police Department','Elmira','NY','USA','There is a safe trading zone in our department parking lot at 317 E. Church St., Elmira, NY'),
('Amberley Village Police Department','Hamilton County','OH','USA','Two dedicated parking spots, video surveillance 24,7'),
('Amherst Police Department','Amherst','OH','USA',null),
('Avon Police Department','Avon','OH','USA','Parking lot available for transactions.'),
('Butler County Sheriff''s Department','Hamilton','OH','USA','Jail lobby, 8 a.m. to 8 p.m. seven days a week.'),
('Cuyahoga Falls Police Department','Cuyahoga Falls','OH','USA','The lobby is open 24 hours a day, 7 days a week. The lobby provides recorded video and audio surveillance.'),
('Dayton Police Department','Dayton','OH','USA','At East Patrol Operations Division North, 417 E. Helena St. and East Patrol Operations Division South, 2721 Wayne Ave. Lobby during regular business hours. Parking lot is also a safe exchange zone.'),
('Delaware County Sheriff''s Office','Delaware','OH','USA','two parking spots at the county jail'),
('Genoa Township','Westerville','OH','USA','Safe zone in the Police station parking lot, marked spaces-lighted and under video surveillance.'),
('Hardin County Sheriff''s Department',null,'OH','USA','Notify the on-duty communications staff upon arrival.'),
('Heath Police Department','Newark','OH','USA','Designated spot in the police station lobby. Activity is recorded.'),
('Lorain Police Department','Avon Lake','OH','USA',null),
('Miami Township','Milford','OH','USA','Two dedicated parking spots, video surveillance 24,7'),
('Massillon Police Department','Canton','OH','USA','Signs are posted outside the Massillon Municipal Courthouse. The parking lot is well lit and under video surveillance.'),
('Medina Township Police Department','Medina Township','OH','USA','Two dedicated parking spots'),
('Toledo Police Department','Toledo','OH','USA','The station is open and police personnel are present 24 hours a day, every single day of the year.'),
('Municipal Justice Center','Warren','OH','USA','An area in the parking lot with 24 hr. surveillance, marked by an e-commerce sign. Parking spaces are painted bright yellow.'),
('Case Western Reserve University Police Department','Cleveland','OH','USA','1689 E. 115th St, Cleveland OH 44106. Transactions can be made in the lobby or parking lot of the police department. Both under 24/7 surveillance.'),
('Broken Arrow Police Department','Broken Arrow','OK','USA',null),
('Oklahoma County Sheriff''s Office',null,'OK','USA','Main office and the Midwest City substation open 24 hours.'),
('Sallisaw Police Department','Sallisaw','OK','USA','Designated parking spots'),
('Sand Springs Police Department','Sand Springs','OK','USA',null),
('Oregon City Police Department','Oregon City','OR','USA','Two designated zones at the Public Safety Building-the public parking lot and building lobby; both zones under 24/7 video surveillance.'),
('Abington Police Department','Abington','PA','USA','The police department lobby is open 24 hours, seven days a week.'),
('Allentown Police Department','Allentown','PA','USA','Two 15-minute parking spaces outside the station have been designated as transaction sites. Spaces are marked with signs and have 24/7 video surveillance.'),
('Bethlehem Township','Bethlehem','PA','USA','2 spaces outlined in green outside the Municipal building, about 20 feet from the entrance to Police headquarters.'),
('Boardman Police Department','Boardman','PA','USA','Designated space in the Police station'),
('Carlisle Police Department','Carlisle','PA','USA','The Carlisle Police Department is open 7 days a week from 7AM-11PM. Residents and visitors are welcome to use the lobby to conduct business or in the front parking lot that is under 24 hour video surveillance.'),
('Conshohocken Police Department','Conshohocken','PA','USA',null),
('Cranberry Township Municipal Center','Cranberry Township','PA','USA','Two parking spaces next to the municipal center have been set aside for online transactions. The spaces are marked by signs and are under video surveillance.'),
('Falls Police Department','Falls','PA','USA',null),
('Forks Township','Forks','PA','USA','safe transaction area in parking lot'),
('Hermitage Police Department','Hermitage','PA','USA','A space in the front parking lot of the police department, designated by red pavement lines and a sign. The zone is lit at night and there might be video surveillance of the area. Designated space in the station, as well.'),
('Kutztown Borough Police Department','Kutztown','PA','USA','Two well lit Exchange Zone parking spots in the front of the Borough Hall/Police Station. Continuous video recording 24/7. Officers do not get involved with any transactions.'),
('Lansdale Police Department','Lansdale','PA','USA','Front parking lot'),
('Lower Merion Police Department','Lower Merion','PA','USA',null),
('Lower Saucon Township','Lower Saucon','PA','USA','Two parking spaces outside station available for transactions. Signs mark exchange area, which is under video surveillance.'),
('Monaca Municipal Building','Monaca','PA','USA','The borough designated two parking spaces for online transactions. The spaces are marked by signs and are under video surveillance.'),
('Muhlenberg Township Police Department','Muhlenberg','PA','USA','2 zones- One in a designated seating area of the Municipal bldg, M-F 8-4:30. After hours zone is a marked area in the back area of the Municipal Bldg parking lot. Both areas monitored by surveillance cameras.'),
('Northhampton Police Department','Northhampton','PA','USA',null),
('Peter''s Township','Peter''s Township','PA','USA',null),
('Philadelphia Police Department','Philadelphia','PA','USA','The spaces are under video surveillance,'),
('Pittsburgh Police Department','Pittsburgh','PA','USA','Two specially-marked parking spaces in front of dept. and City Hall'),
('South Fayette Township Police Department','South Fayette Township','PA','USA','"Internet Purchase Exchange Location" in front of police station'),
('Springettsbury Police Department','Springettsbury','PA','USA','Lobby or designated spaces in the parking lot. The lobby is open 8 a.m. to 5 p.m. M-F; parking lot and lobby have 24-hour video surveillance.'),
('Upper Darby Police Department','Upper Darby Township','PA','USA','Lower lobby and the area just outside of the front door of the station'),
('Upper Saucon Township Police Department','Center Valley','PA','USA','Two spaces in front of the police station marked by a Safe Trade Station sign under continuous video surveillance.'),
('Upper Southampton Police Department','Upper Southhampton','PA','USA','The area behind Police Headquarters is a designated Safe Exchange Zone. It is a brightly lit area recorded by multiple cameras.'),
('Westtown-East Goshen Regional Police Department','West Chester','PA','USA','Lobby weekdays 9:00 am and 3:00 pm. Also 2 "SafeTrade" parking spaces directly in front of building'),
('Yardley Police Department','Yardley Borough','PA','USA',null),
('York City Police Department','York City','PA','USA',null),
('Pawtucket Police Department','Pawtucket','RI','USA',null),
('Greer Police Department','Greer','SC','USA','Two parking spots; 24/7 video surveillance'),
('Kershaw County Sheriff''s office',null,'SC','USA',null),
('Moncks Corner Police Department','Moncks','SC','USA','Municipal office and police department on Carolina Avenue (lot). The area is monitored 24/7 by cameras for added security'),
('Mount Pleasant Police Department','Mount Pleasant','SC','USA',null),
('Newberry County Sheriff''s office','Newberry','SC','USA',null),
('West Columbia Police Department','West Columbia','SC','USA',null),
('Beaufort County Sheriff''s Office',null,'SC','USA',null),
('Bluffton Police Department','Bluffton','SC','USA',null),
('Richland County Sheriff''s Department',null,'SC','USA','"Internet Exchange Safety Zone" signs are located in the parking lots of the Richland County Sheriff''s Department''s main Headquarters, Region 1 Headquarters, Region 3 Headquarters, Region 4 Headquarters, and Region 6 Headquarters.'),
('Tega Cay Police Department','Tega Cay','SC','USA','Two designated parking spaces with "Internet Purchase Exchange Location" signage. Both the parking lot and lobby are under video surveillance.'),
('Georgetown Police Department','Georgetown','SC','USA','Trades can be made in the lit public parking lot 24/7 at 1134 N. Fraser Street Georgetown, SC 29440'),
('Hardeeville Police Department','Hardeeville','SC','USA','OfferUp has donated a Meetup Spot sign that has been placed in our parking lot. The spot is very lit up and has a 24-hour video camera recording. 26 Martin St. Hardeeville, SC 29927.'),
('The Mitchell Police Department','The Mitchell','SD','USA','Area in parking lot with 24/7 video surveillance'),
('Sioux Falls Police Department','Sioux Falls','SD','USA',null),
('Chattanooga Police Department','Chattanooga','TN','USA','Designated Safe Exchange Zone with signage and parking spaces.'),
('Dalton Police Department','Dalton','TN','USA',null),
('Dickson Police Department','Dickson','TN','USA',null),
('Henry County Sheriff''s Office','Paris','TN','USA','Parking lot with 24 hour video surveillance'),
('Lebanon Police Department','Lebanon','TN','USA','Allocated spaces outside 2 police stations. Both under 24 hour surveillance. One station allows gun sales.'),
('McNairy County Sheriff''s Office','McNairy','TN','USA',null),
('Mt. Juliet Police Department','Mt Juliet','TN','USA','Parking lot available for use'),
('Gallatin Police Department','Gallatin','TN','USA',null),
('Murfreesboro Police Department','Murfreesboro','TN','USA','Parking lot has marked spaces under video surveillance 24/7.'),
('Nashville Metro Police Departments','Nashville','TN','USA','Monitored spaces in parking Department parking lots with video surveillance. Includes La Vergne, Goodlettsville, Hendersonville and Spring Hill.'),
('Smyrna Police Department','Smyrna','TN','USA','Parking lot available for use.'),
('Bedford Police Department','Bedford','TX','USA',null),
('Benbrook Police Department','Benbrook','TX','USA',null),
('Brownsville Police Department','Brownsville','TX','USA',null),
('Cedar Park Police Department','Cedar Park','TX','USA','The Police Department''s parking lot and lobby are monitored by 24-hour surveillance cameras and are located in well lit, public spaces.'),
('Corpus Christie Police Department','Corpus Christie','TX','USA','2 designated parking spaces at 4 library locations'),
('Denison Police Department','Denison','TX','USA','Parking spaces on east side of building, marked with paint on pavement'),
('Flower Mound Police Department','Flower Mound','TX','USA',null),
('Fort Worth Police Department','Fort Worth','TX','USA',null),
('Fulshear Police Department','Fulshear','TX','USA','Call in advance.'),
('Georgetown Police Department','Georgetown','TX','USA','Lobby available during business hours. 24 hour use of parking lot. All sales are civil matters. Officers should not be called on to intervene.'),
('Haltom City Police Department','Haltom City','TX','USA','Lobby open 24-7. Lobby camera monitored. No large objects (appliances, furniture etc) or vehicles with trailers.'),
('La Porte Police Department','La Porte','TX','USA',null),
('Leander Police Department','Leander','TX','USA','Front of police station is marked and under camera surveillance. No use of lobby. Weapons, medications, and other unlawful items are prohibited.'),
('Longview Police Department','Longview','TX','USA','Parking spaces in front'),
('Lubbock Police Department','Lubbock','TX','USA','Safe Exchange spaces at the side of the Texas Avenue building under 24 hour surveillance.'),
('Manor Police Department','Manor','TX','USA','Police lobby available during business hours 8am to 5pm. 24 hour use of parking lot which is under video surveillance and well lit.'),
('Palestine Police Department','Palestine','TX','USA','A sign is posted over two blue-lined parking spots in the PD parking lot. Spots are monitored 24/7 and recorded.'),
('Pflugerville Police Department','Pflugerville','TX','USA','Lobby during normal business hours (daylight), 24-hour parking lot'),
('Precinct 2 Constable''s Office','Noonday','TX','USA','Parking lot'),
('Precinct 5 Constable''s Office','Lindale','TX','USA','Parking lot'),
('Round Rock Police Department','Round Rock','TX','USA','Dept. public parking area and lobby are designated Safety Exchange Zones. Lobby is open M – F 8 a.m. to 5 p.m. Parking lot is open 24/7. Zones are well lit and under 24/7 surveillance.'),
('San Antonio Police Department Substations Only','San Antonio','TX','USA','There are designated parking spaces at all 6 substations that are monitored by camera. Exchanges can also take place in a substation lobby.'),
('San Marcos Police Department','San Marcos','TX','USA','Two parking spaces out front lobby access available, both 24/7. All videotaped.'),
('Smith County Emergency Operations Center','Tyler','TX','USA','West parking lot'),
('Sunset Valley Texas','Sunset Valley','TX','USA','Police station parking lot and lobby (during normal business hours)'),
('Howe Police Department','Howe','TX','USA','700 West Haning Street, Howe TX 75459. We have created a safe exchange zone for our citizens at the Howe Police Department.'),
('Angelina County Sheriff''s Office','Lufkin','TX','USA','2311 E Lufkin Ave, Lufkin, TX 75901. There are 3 spots marked in white in front of the Sheriff''s department, transactions can be made 24/7'),
('City of Whitehouse Police Department','Whitehouse','TX','USA','Our safe exchange is located at 101 Bascom Road, Whitehouse Texas. It is recorded 24 hours a day and staff is present during business hours M-F 8:30-4:30.'),
('Tooele City Police Department','Tooele','UT','USA','Parking lot during daylight hours. Police personnel will not be involved.'),
('Abingdon Police Department','Abingdon','VA','USA','Parking lot'),
('Albemarle Police County Department','Albemarle','VA','USA','Safe Exchange signs'),
('Chesterfield Sheriff''s Office','Chesterfield','VA','USA','At the main courthouse and painted blue'),
('Fairfax City Police Department','Fairfax','VA','USA','Parking lot designated spaces'),
('Fredricksburg Police Department','Fredricksburg','VA','USA','Parking lot'),
('Leesburg Police Department','Leesburg','VA','USA','The zone is located in the front parking lot and is well lit and monitored by security cameras. Residents also have the ability to conduct their transactions in the main lobby of the building, open 24 hours a day.'),
('Petersburg County Sheriff''s Office','Petersburg','VA','USA','Lobby and parking lot'),
('Manassas City Police Department','Manassas','VA','USA','Zones in front of the station with 24 hr surveillance. 15 minute spaces for child custody exchanges.'),
('Spotsylvania County Sheriff''s Office','Spotsylvania','VA','USA','Parking lot'),
('Stafford County Sheriff''s Office','Stafford','VA','USA','Two designated parking spots plus lobby vestibule'),
('Suffolk Police Department','Suffolk','VA','USA','Stations at Police Headquarters and the department''s Sector II Precinct. 24 hour surveillance in the lobby and around the building.'),
('Virginia Beach Police','Virginia Beach','VA','USA','9am to 9pm. No large household items, appliances, or lawn care equipment.'),
('Winchester Police Department','Winchester','VA','USA','Lobby of the Public Safety Center.'),
('Vinton Police Department','Roanoke','VA','USA','All of the safe exchange zones in our area have 24-hour surveillance and are very close to local law enforcement'),
('Lexington Police Department','Lexington','VA','USA','11 Fuller St, Lexington, VA 24450. Trades can be made in the parking lot.'),
('Virginia Commonwealth University','Richmond','VA','USA','We have a lighted area under video surveillance in our vestibule at 224 E. Broad Street, Richmond, VA 23284'),
('Virginia Tech Police Department','Blacksburg','VA','USA','There is a well lit and marked SafeTrade Station at 330 Sterrett Drive Suite, Blacksburg, VA 24061. This location is recorded 24-7 and located in the front of the police department'),
('Bellingham Police Department','Bellingham','WA','USA','Designated spaces with surveillance'),
('Des Moines Police Department','Des Moines','WA','USA','The police department parking lot is well lit and under 24 hour video surveillance'),
('Kent Police Department','Kent','WA','USA','Designated space in the PD parking lot.'),
('Lakewood Police Department','Lakewood','WA','USA','Police station lobby, parking lot available for buyers, sellers. Lobby is under constant surveillance and is open Monday through Friday, 9 a.m. to 5 p.m., with a staffed front counter.'),
('Marysville','Marysville','WA','USA','Two designated parking spots in the southeast corner of the police station parking lot.'),
('Sedro-Woolley','Sedro-Woolley','WA','USA','Two designated parking spaces'),
('Appleton Police Department','Appleton','WI','USA',null),
('Delton Fire Department and EMS facility','Lake Delton','WI','USA','Sign posted in the northwest parking lot'),
('Greenfield Police Department','Greenfield','WI','USA','Parking lot'),
('Hortonville Police Department','Hortonville','WI','USA','Sign designating the area which is monitored 24/7 by a camera, lighted and located right outside police department'),
('Lincoln County Sheriff''s Office','Merrill','WI','USA','Parking lot'),
('New London','New London','WI','USA','Transaction should take place in front of the police station, on the sidewalk on the north side entryway, in front of any vehicles, to be visible on surveillance.'),
('Oshkosh Police Department','Oshkosh','WI','USA','Exchange location is in the lobby of the Jackson St. station.'),
('Portage County Sheriff''s Department','Stevens Point','WI','USA','2 Designated parking spot in front of Police Station under video surveillance'),
('Racine Police Department','Racine','WI','USA',null),
('West Allis','West Allis','WI','USA','Transactions can be made in the lobby or parking lot of the police department. Both under 24/7 surveillance.'),
('Platteville Police Department','Platteville','WI','USA','2 marked parking spaces outside the police department under video surveillance.'),
('Beaumont RMCP','Beaumont','Alberta','Canada','Exchange Zone at the Detachment during business hours M-W-F 8:30-5:30. Th 8:30-7'),
('Calgary Police Service','Calgary','Alberta','Canada','Parking lots at all district offices'),
('Edmonton Police Department','Edmonton','Alberta','Canada','2 dedicated spaces outside the southwest division, under video surveillance 24/7.'),
('Abbotsford Police Department','Abbotsford','BC','Canada','2 designated spots in front of the police station with 24 hr video surveillance.'),
('Vancouver Police Department','Vancouver','BC','Canada',null),
('Winnipeg Police Department','Winnipeg','Manitoba','Canada','Safe Exchange zones in all 4 main police stations. Area is under video surveillance.'),
('Truro Police Station','Truro','NS','Canada','Station is manned 24/7'),
('Peel Regional Police','Brampton','ON','Canada','Two dedicated, signed parking spaces at 22 Division that are monitored by surveillance cameras'),
('Manitoulin Detachment of the OPP','Little Current','ON','Canada','A signed, designated area on Campbell St. in front of the Little Current Detachment.'),
('Midland Police Department','Midland','ON','Canada',null),
('Orangeville Police Department','Orangeville','ON','Canada',null),
('Smiths Falls Police Station','Smiths Falls','ON','Canada','A parking space — monitored 24-7 — will be allocated at the Smiths Falls police station located at 7 Hershey Dr.'),
('Saskatoon Police Service','Saskatoon','Saskatchewan','Canada','Signed safe exchange zone in the police headquarters'' visitor parking lot.'),
('Wetaskiwin RMCP','Wetaskiwin',null,'Canada',null),
('Rio Negro Police Department','Rio Negro','Paraná','Brazil','2 Designated parking spaces, "Área Segura", in front of the police station, under video surveillance, 24/7.'),
('College Station Police Department','College Station','TX','USA',null),
('Grapevine Police Department','Grapevine','TX','USA','Signed, dedicated parking spaces in front of the Public Safety Building, under 24/7 surveillance.');

alter table public.listings
  add column pickup_enabled boolean not null default false,
  add column pickup_station_id uuid references public.pickup_stations(id);

-- create_listing_with_details gains two trailing pickup params. Same 20-arg live signature as
-- 202609300054_signature_reference_library.sql -- dropped explicitly (a changed param count
-- always needs this, or PostgREST calls resolved by named args become ambiguous between overloads,
-- same failure mode documented at 202609300046_signature_media_kind.sql).
drop function public.create_listing_with_details(text,text,text,bigint,text,text,text,text,jsonb,jsonb,jsonb,numeric,numeric,numeric,numeric,boolean,text,integer,text,text);
create function public.create_listing_with_details(
  p_title text,p_description text,p_category text,p_price_cents bigint,p_evidence text default '',
  p_issuer text default null,p_number text default null,p_company text default null,p_media jsonb default '[]',
  p_attributes jsonb default '{}',p_tags jsonb default '[]',
  p_weight_oz numeric default null,p_length_in numeric default null,p_width_in numeric default null,p_height_in numeric default null,
  p_free_shipping boolean default false,
  p_listing_type text default 'fixed',p_auction_days integer default null,
  p_signature_ai_label text default null,p_signature_ai_note text default null,
  p_pickup_enabled boolean default false,p_pickup_station_id uuid default null
) returns uuid language plpgsql security definer set search_path='' as $$
declare new_id uuid; field record; tag jsonb; clean_attributes jsonb:='{}'; clean_tags jsonb:='[]'; clean text;
  allowed text[]:=array['item_type','subject','year','condition','grading_company','grade'];
begin
  if p_listing_type not in ('fixed','auction') then raise exception 'Invalid listing type.'; end if;
  if p_listing_type='auction' and p_auction_days not in (3,5,7) then raise exception 'Choose a 3, 5, or 7 day auction.'; end if;
  if p_category='Sports' then allowed:=allowed||array['sport','team'];
  elsif p_category='Art' then allowed:=allowed||array['artist','medium','dimensions'];
  elsif p_category='Comics' then allowed:=allowed||array['publisher','issue']; end if;
  if p_attributes is null or jsonb_typeof(p_attributes)<>'object' then raise exception 'Invalid item details'; end if;
  for field in select * from jsonb_each(p_attributes) loop
    if not(field.key=any(allowed)) or jsonb_typeof(field.value)<>'string' then raise exception 'Unsupported item detail'; end if;
    clean:=btrim(field.value#>>'{}');
    if length(clean)>120 then raise exception 'Item detail too long'; end if;
    if clean<>'' then clean_attributes:=clean_attributes||jsonb_build_object(field.key,clean); end if;
  end loop;
  if p_tags is null or jsonb_typeof(p_tags)<>'array' then raise exception 'Invalid tags'; end if;
  for tag in select * from jsonb_array_elements(p_tags) loop
    if jsonb_typeof(tag)<>'string' then raise exception 'Invalid tag'; end if;
    clean:=lower(regexp_replace(btrim(tag#>>'{}'),'\s+',' ','g'));
    if length(clean)>40 then raise exception 'Tag too long'; end if;
    if clean<>'' and not(clean_tags ? clean) then clean_tags:=clean_tags||jsonb_build_array(clean); end if;
  end loop;
  if jsonb_array_length(clean_tags)>8 then raise exception 'Too many tags'; end if;
  if p_weight_oz is null or p_weight_oz<=0 or p_length_in is null or p_length_in<=0
     or p_width_in is null or p_width_in<=0 or p_height_in is null or p_height_in<=0 then
    raise exception 'Enter a valid package weight and size.';
  end if;
  if p_pickup_enabled and not exists(select 1 from public.pickup_stations where id=p_pickup_station_id) then
    raise exception 'Choose a valid pickup location.';
  end if;
  new_id:=public.create_listing_with_media(p_title,p_description,p_category,p_price_cents,p_evidence,p_issuer,p_number,p_company,p_media);
  update public.listings set attributes=clean_attributes,tags=clean_tags,
    weight_oz=p_weight_oz,length_in=p_length_in,width_in=p_width_in,height_in=p_height_in,free_shipping=coalesce(p_free_shipping,false),
    listing_type=p_listing_type,auction_ends_at=case when p_listing_type='auction' then now()+make_interval(days=>p_auction_days) else null end,
    signature_ai_label=p_signature_ai_label,signature_ai_note=nullif(btrim(coalesce(p_signature_ai_note,'')),''),
    pickup_enabled=coalesce(p_pickup_enabled,false),pickup_station_id=case when p_pickup_enabled then p_pickup_station_id else null end
    where id=new_id;
  perform public.capture_signature_reference(new_id, clean_attributes->>'subject', p_signature_ai_note);
  perform public.notify_klaviyo((select email from auth.users where id=auth.uid()),'Item Listed',
    jsonb_build_object('listing_id',new_id,'title',p_title,'category',p_category,'price_cents',p_price_cents,'listing_type',p_listing_type));
  return new_id;
end;
$$;
revoke all on function public.create_listing_with_details(text,text,text,bigint,text,text,text,text,jsonb,jsonb,jsonb,numeric,numeric,numeric,numeric,boolean,text,integer,text,text,boolean,uuid) from public,anon;
grant execute on function public.create_listing_with_details(text,text,text,bigint,text,text,text,text,jsonb,jsonb,jsonb,numeric,numeric,numeric,numeric,boolean,text,integer,text,text,boolean,uuid) to authenticated;

-- browse_listings_with_certificates(): 0-arg, plain create or replace (no drop needed -- the
-- param list is unchanged). Adds pickup_enabled and a denormalized pickup_station object (so the
-- frontend never needs a second round-trip to show the station's name/city/notes).
create or replace function public.browse_listings_with_certificates() returns jsonb
language sql stable security definer set search_path='' as $$
select coalesce(jsonb_agg(item || jsonb_build_object(
  'attributes',l.attributes,'tags',l.tags,'seller_charges_enabled',coalesce(sa.charges_enabled,false),
  'seller_member_since',p.created_at,
  'seller_sales_count',(select count(*) from public.purchases where seller_id=l.seller_id),
  'seller_rating_avg',(select round(avg(rating)::numeric,2) from public.seller_ratings where seller_id=l.seller_id),
  'seller_rating_count',(select count(*) from public.seller_ratings where seller_id=l.seller_id),
  'pickup_enabled',l.pickup_enabled,
  'pickup_station',case when l.pickup_enabled then jsonb_build_object('id',ps.id,'jurisdiction',ps.jurisdiction,'city',ps.city,'state',ps.state,'country',ps.country,'notes',ps.notes) else null end
) order by position),'[]'::jsonb)
from jsonb_array_elements(public.browse_listings_with_media()) with ordinality as items(item,position)
join public.listings l on l.id=(item->>'id')::uuid
join public.profiles p on p.id=l.seller_id
left join public.stripe_accounts sa on sa.user_id=l.seller_id
left join public.pickup_stations ps on ps.id=l.pickup_station_id;
$$;

-- my_open_buy_requests(): the buyer's own path into CheckoutAddress when reached via the buy-
-- request flow (rather than browse) -- needs the identical pickup fields or the choice silently
-- fails to render on that code path. 0-arg, plain create or replace.
create or replace function public.my_open_buy_requests() returns jsonb
language sql stable security definer set search_path='' as $$
  select coalesce(jsonb_agg(jsonb_build_object(
    'id',r.id,'listing_id',l.id,'title',l.title,'category',l.category,'price_cents',l.price_cents,'status',r.status,'expires_at',r.expires_at,
    'pickup_enabled',l.pickup_enabled,
    'pickup_station',case when l.pickup_enabled then jsonb_build_object('id',ps.id,'jurisdiction',ps.jurisdiction,'city',ps.city,'state',ps.state,'country',ps.country,'notes',ps.notes) else null end,
    'media',coalesce((select jsonb_agg(jsonb_build_object('path',m.path,'kind',m.kind) order by m.position) from public.listing_media m where m.listing_id=l.id and m.kind='item'),'[]'::jsonb)
  ) order by r.created_at desc),'[]'::jsonb)
  from public.availability_requests r join public.listings l on l.id=r.listing_id
  left join public.pickup_stations ps on ps.id=l.pickup_station_id
  where r.buyer_id=auth.uid() and r.status in ('pending','confirmed') and r.expires_at>now();
$$;

commit;
